# -*- coding: utf-8 -*-
"""calculadora simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQWHVkQ-6_G2bqdrjwG8PGWRo5LgeLnW
"""

# Coletamos os números a serem operados e solicitamos a operação desejada pela pessoa usuária
num1 = float(input('Informe o primeiro número: '))
num2 = float(input('Informe o segundo número: '))
operacao = input('Informe a operação desejada (+, -, *, /): ')

# Verificamos o operador que foi selecionado e executa a operação matemática conforme a seleção
if operacao == '+':
    resultado = num1 + num2

elif operacao == '-':
    resultado = num1 - num2

elif operacao == '*':
    resultado = num1 * num2

elif operacao == '/':
    resultado = num1 / num2

else: # Especificamos um resultado caso a pessoa usuária não digite alguma das operações corretamente.
    print('Operação inválida, resultado da operação será 0')
    resultado = 0

# Imprimimos o resultado da operação
print(f'Resultado da operação {num1} {operacao} {num2}: ', resultado)