# -*- coding: utf-8 -*-
"""mini_projeto_morse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EYDljsooEId0OFzsPCwERiC4Dm4I2NYM
"""

abc_morse = {'a':'.-', 'b':'-..', 'c':'-.-', 'd':'-..', 'e':'.',
             'f':'..-.', 'g':'--.', 'h':'....', 'i':'..', 'j':'.--',
             'k':'-.-', 'l':'.-..', 'm':'--', 'n':'-.', 'o':'---',
             'p':'.--.', 'q':'--.-', 'r':'.-.', 's':'...', 't':'-',
             'u':'..-', 'v':'...-', 'w':'.--', 'x':'-..-', 'y':'-.--',
             'z':'--..', ' ':' ', '1':'.---', '2':'..---', '3':'...--', '4':'....-',
             '5':'.....', '6':'-....', '7':'--...', '8':'---..', '9':'----.', '0':'-----',
             '&': '.-...', "'": '.----.', '@': '.--.-.', ')': '-.--.-', '(': '-.--.',
             ':': '---...', ',': '--..--', '=': '-...-', '!': '-.-.--', '.': '.-.-.-',
             '-': '-....-', '+': '.-.-.', '"': '.-..-.', '?': '..--..', '/': '-..-.'
              }


def codificador():
    frase = str(input('Qual frase você quer codificar?\n'))
    morse = ""

    for letra in frase:

        morse += abc_morse[letra.lower()]+ ' '

    print(f'\nCódigo morse para "{frase}":')
    return print(morse)

codificador()